customCommands:
  containers:
  - name: EnterContainers
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
  images:
  - name: RemoveTag
    attach: true
    command: docker rmi {{ .Repository }}
    serviceNames: []
