# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[container]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true


[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 16
truncate_to_repo = false

[git_status]
disabled=true

[git_commit]
disabled=true

[git_state]
disabled=true

[git_metrics]
disabled=true

